name: Slack
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: hard-braking
    required: true
  - name: webhook_url
    inputType: FreeText
    description: The webhook url to send notifications to
    defaultValue: adasdasda
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
