name: superbase-sink
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: clickstream-group-by-page
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
