name: Heatmap frontend
language: nodejs
variables:
  - name: click_topic
    inputType: OutputTopic
    description: ''
    defaultValue: click-data
    required: false
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
