name: heatmap-stage
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: clickstream-group-by-page
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: heatmap
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
